server:
  servlet:
    context-path: /api
  port: 8080

spring:
  thymeleaf:
    cache: false
  redis:
    host: 172.16.99.178
    password: foobared123
    port: 6388
    timeout: 3000
    database: 0
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 0
        max-wait: 3000
    client-type: lettuce

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.16.99.82:3306/test?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    password: root
    username: root
mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml
xm:
  starter:
    base:
      rvo-excluded-patterns:
        - /logVisual/view
    log-visual:
      enable: true
      path:
        - E:\logs\sc-scm
        - E:\logs\sc-supplier
    auth:
      enable: true
      exclude-path-patterns:
        - /sysUser/login
        - /logVisual/**
    file:
      enable: true
      local-file-config:
        domain: http://172.16.99.82/liyi99-local-file
        rootPath: E:\\upload\\local-file
      oss-file-config:
        endpoint: https://oss-cn-shenzhen.aliyuncs.com
        url-expiration-millisecond: 315360000000
        bucket-name: liyi99-pic
        access-key-secret:
        access-key-id:
    request:
      log:
        enable: true
    logback:
      output:
        ding-ding-config:
          enable: true
        xxl-job-config:
          enable: true
        enable: true
    task:
      enable: true
